# Dockerfile.emi
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the entire project
COPY . .
# Copy expertIds.csv from its actual location in the repo
COPY src/backend/etl/aggieExpertsAPI/utils/expertIds.csv ./src/backend/etl/aggieExpertsAPI/utils/expertIds.csv

# Build the React app
RUN npm run build

EXPOSE 3001
CMD ["node", "src/backend/server.js"]
