# Dockerfile.backend
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy only backend code
COPY src/backend ./src/backend

EXPOSE 3001
CMD ["node", "src/backend/server.js"]
