services:
  emi-app:
    image: emi
    build:
      context: .
      dockerfile: Dockerfile.emi
    container_name: emi-app
    ports:
      - "80:3000"     # Frontend
      - "3001:3001"   # Backend
    environment:
      - OLLAMA_HOST=http://34.168.196.77:11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgis
      - PG_PORT=5432
      - PG_DATABASE=emi
      - PG_USER=postgres
      - PG_PASSWORD=emiencrypted
    depends_on:
      - redis
      - postgis
    command: sh -c "npm start & node src/backend/server.js"

  redis:
    image: redis
    container_name: emi-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped

  postgis:
    image: postgis/postgis
    container_name: emi-postgis
    environment:
      POSTGRES_DB: emi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emiencrypted
    ports:
      - "5432:5432"
    volumes:
      - ./postgis-data:/var/lib/postgresql/data
      - ./init-pg:/docker-entrypoint-initdb.d
    restart: unless-stopped