# Dockerfile.emi
FROM node:18-alpine

# Enable vm-local editing
RUN apk add --no-cache nano

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the entire project
COPY . .

# Build the React app
RUN npm run build

EXPOSE 3001
CMD ["node", "src/backend/server.js"]
