name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  # --- Job 1: Build, Test, and Process Data ---
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      # Fetches the latest code from the repository branch that triggered the workflow.
      - name: Checkout code
        uses: actions/checkout@v4

      # Installs the specified version of Node.js and configures caching for npm dependencies.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Installs all necessary Node.js packages defined in package-lock.json.
      - name: Install dependencies
        run: npm install

      # Generates a .env file containing connection details and API keys needed by the application using github repo secrets.
      - name: Create .env file
        run: |
          # External PostgreSQL Database connection details
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env # Hostname of the external PostgreSQL server
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env # Port number for the PostgreSQL server
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env # Username for the PostgreSQL database
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env # Password for the PostgreSQL database
          echo "PG_DATABASE=${{ secrets.PG_DATABASE }}" >> .env # Name of the PostgreSQL database

          # External Redis Database connection details
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env # Hostname of the external Redis server
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env # Port number for the Redis server

          # Backend Redis Database connection details
          echo "BACKEND_REDIS_PORT=${{ secrets.BACKEND_REDIS_PORT }}" >> .env # Port number for the Redis server

          # API Authentication Token
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env # Token needed to authenticate with the Aggie Experts API

      # Compiles the React frontend code into static assets for deployment.
      - name: Build project
        run: npm run build 
        continue-on-error: false

      # Saves the built React application (from the './build' directory) as an artifact.
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./build
          retention-days: 1

  # --- Job 2: Deploy to GitHub Pages ---
  deploy-to-github-pages:
    environment:
      name: github-pages

    needs: build-and-test

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write # Permission to write to GitHub Pages
      id-token: write # Permission for OIDC token authentication (secure deployment)

    steps:
      # Checkout code again in this job
      - name: Checkout code
        uses: actions/checkout@v4

      # Retrieves the 'build-output' artifact saved by the 'build-and-test' job.
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      # Verify the build folder contents
      - name: Check build folder
        run: |
          ls -la
          ls -la build || echo "Build folder not found"

      # Sets up the runner environment for deploying to GitHub Pages.
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Uploads the downloaded build directory specifically for the Pages deployment action.
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Path to the directory containing the static site

      # Executes the actual deployment to GitHub Pages using the uploaded artifact.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4